### ISSUE TITLE
500 error when no longditude/latitude/radius specified

### ISSUE THREAD

**Issue by jonnor** [flowhub/bigiot-bridge#56]
Probably we should have some default values, probably returning all data.
Or alternatively return a 422 with descriptive error message.

**Comment by jonnor** [comment]
```
2018-09-12T19:35:36.870243+00:00 app[web.1]: command: 'GEORADIUS',
2018-09-12T19:35:36.870245+00:00 app[web.1]: args: [ 'cologne-spaces', NaN, NaN, 100, 'm' ],
2018-09-12T19:35:36.870246+00:00 app[web.1]: code: 'ERR' }
2018-09-12T19:35:36.969647+00:00 app[web.1]: { ReplyError: ERR value is not a valid float
2018-09-12T19:35:36.969651+00:00 app[web.1]: at parseError (/app/node_modules/redis-parser/lib/parser.js:193:12)
2018-09-12T19:35:36.969655+00:00 app[web.1]: at parseType (/app/node_modules/redis-parser/lib/parser.js:303:14)
2018-09-12T19:35:36.969657+00:00 app[web.1]: 
2018-09-12T19:35:36.969659+00:00 app[web.1]: command: 'GEORADIUS',
2018-09-12T19:35:36.969660+00:00 app[web.1]: args: [ 'parkspaces', NaN, NaN, 100, 'm' ],
2018-09-12T19:35:36.969662+00:00 app[web.1]: code: 'ERR' }
2018-09-12T19:35:37.000728+00:00 app[web.1]: at parseError (/app/node_modules/redis-parser/lib/parser.js:193:12)
2018-09-12T19:35:37.000725+00:00 app[web.1]: { ReplyError: ERR value is not a valid float
2018-09-12T19:35:37.000730+00:00 app[web.1]: at parseType (/app/node_modules/redis-parser/lib/parser.js:303:14)
2018-09-12T19:35:37.000731+00:00 app[web.1]: 
2018-09-12T19:35:37.000733+00:00 app[web.1]: command: 'GEORADIUS',
2018-09-12T19:35:37.000736+00:00 app[web.1]: code: 'ERR' }
2018-09-12T19:35:37.088754+00:00 app[web.1]: { ReplyError: ERR value is not a valid float
2018-09-12T19:35:37.000735+00:00 app[web.1]: args: [ 'cologne-spaces', NaN, NaN, 100, 'm' ],
2018-09-12T19:35:37.088757+00:00 app[web.1]: at parseError (/app/node_modules/redis-parser/lib/parser.js:193:12)
2018-09-12T19:35:37.088759+00:00 app[web.1]: at parseType (/app/node_modules/redis-parser/lib/parser.js:303:14)
```
